const courses = [
  { name: "NFPA 101" },
  { name: "PTCRB" },
  { name: "WCAG" },
  { name: "Cisco IOS" },
  { name: "TDMoIP" },
  { name: "IP Networking" },
  { name: "Administration" },
  { name: "CMYK" },
  { name: "IT Strategy" },
  { name: "HDI Support Center Analyst" },
  { name: "Photography" },
  { name: "Labor Relations" },
  { name: "PVM" },
  { name: "EGPRS" },
  { name: "Business Intelligence Tools" },
  { name: "Rsync" },
  { name: "Time Series Analysis" },
  { name: "Software Engineering" },
  { name: "Electronic Warfare" },
  { name: "HSUPA" },
  { name: "Type 2 Diabetes" },
  { name: "Brand Development" },
  { name: "Organizational Leadership" },
  { name: "Zend" },
  { name: "Regulatory Affairs" },
  { name: "Rail" },
  { name: "Djbdns" },
  { name: "WBS" },
  { name: "MW" },
  { name: "Lyric Soprano" },
  { name: "Young Adult Literature" },
  { name: "Orchestral Music" },
  { name: "NWDS" },
  { name: "JRuby" },
  { name: "Control Systems Design" },
  { name: "MBOX" },
  { name: "Gymnastics" },
  { name: "VBScript" },
  { name: "NVivo" },
  { name: "EIGRP" },
  { name: "Zabbix" },
  { name: "Heavy Oil" },
  { name: "Strategic Sourcing" },
  { name: "NHS" },
  { name: "TCD" },
  { name: "MRV" },
  { name: "EPM" },
  { name: "Emergency Management" },
  { name: "Site Development" },
  { name: "NVivo" },
  { name: "CP" },
  { name: "Ecological Restoration" },
  { name: "PDO" },
  { name: "HCV" },
  { name: "PTO" },
  { name: "DGA" },
  { name: "Warranty" },
  { name: "Oxy-acetylene" },
  { name: "ALM" },
  { name: "JDOM" },
  { name: "Bathrooms" },
  { name: "Client Relations" },
  { name: "CFDesign" },
  { name: "Zooarchaeology" },
  { name: "QIP" },
  { name: "Type Design" },
  { name: "Estate Jewelry" },
  { name: "Non-profit Leadership" },
  { name: "JMeter" },
  { name: "Operational Excellence" },
  { name: "FMECA" },
  { name: "RNA" },
  { name: "Biostatistics" },
  { name: "Occupational Medicine" },
  { name: "Rhetorical Analysis" },
  { name: "UDDI" },
  { name: "Bookkeeping" },
  { name: "LPG" },
  { name: "VGA" },
  { name: "SSI" },
  { name: "Sony Vegas" },
  { name: "JReport" },
  { name: "Troubleshooting" },
  { name: "Robotics" },
  { name: "Construction" },
  { name: "ERP Implementations" },
  { name: "Documentaries" },
  { name: "MyChart" },
  { name: "Veterinary" },
  { name: "Yarn" },
  { name: "UCC filings" },
  { name: "Kinect" },
  { name: "EP" },
  { name: "International Business" },
  { name: "Site Planning" },
  { name: "iView" },
  { name: "Environmental Policy" },
  { name: "Jewish Education" },
  { name: "GPU" },
  { name: "AMBA AHB" },
];

module.exports = { courses };
